import { useEffect, useMemo, useState } from "react";
import "./App.css";

const API_BASE = "https://fitnessforge-api-2026.onrender.com";
const fallbackPlan = { goal:"General Fitness", level:"Beginner", fitness_score:65, workout_type:"General Fitness", intensity:"Low to Moderate", duration:"25 minutes", workout:["Bodyweight Squats","Push Ups","Plank","Stretching"] };
const navItems = [["dashboard","⌂","Dashboard"],["workouts","◈","Workouts"],["nutrition","◉","Nutrition"],["progress","↗","Progress"],["profile","♙","Profile"]];

function App(){
 const [darkMode,setDarkMode]=useState(true),[activePage,setActivePage]=useState("dashboard"),[showAssessment,setShowAssessment]=useState(false),[showProfile,setShowProfile]=useState(false);
 const [goal,setGoal]=useState(localStorage.getItem("ff_goal")||"General Fitness"),[level,setLevel]=useState(localStorage.getItem("ff_level")||"Beginner");
 const [plan,setPlan]=useState(()=>{try{return {...fallbackPlan,...JSON.parse(localStorage.getItem("ff_plan")||"{}")}}catch{return fallbackPlan}});
 const [profile,setProfile]=useState(()=>{try{return {name:"Fitness Explorer",age:"",height:"",weight:"",gender:"Prefer not to say",activity:"Moderately Active",...JSON.parse(localStorage.getItem("ff_profile")||"{}")}}catch{return {name:"Fitness Explorer",age:"",height:"",weight:"",gender:"Prefer not to say",activity:"Moderately Active"}}});
 const [completed,setCompleted]=useState(()=>{try{return JSON.parse(localStorage.getItem("ff_completed")||"[]")}catch{return []}});
 const [loading,setLoading]=useState(false),[apiOnline,setApiOnline]=useState(false),[toast,setToast]=useState("");
 useEffect(()=>{fetch(`${API}/health`).then(r=>r.ok?r.json():Promise.reject()).then(()=>setApiOnline(true)).catch(()=>setApiOnline(false))},[]);
 useEffect(()=>{localStorage.setItem("ff_goal",goal);localStorage.setItem("ff_level",level);localStorage.setItem("ff_plan",JSON.stringify(plan));localStorage.setItem("ff_profile",JSON.stringify(profile));localStorage.setItem("ff_completed",JSON.stringify(completed))},[goal,level,plan,profile,completed]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2500);return()=>clearTimeout(t)},[toast]);
 const exercises=plan.workout||[], completion=exercises.length?Math.round(completed.filter(x=>exercises.includes(x)).length/exercises.length*100):0;
 const calories=useMemo(()=>{let w=+profile.weight,h=+profile.height,a=+profile.age;if(!w||!h||!a)return 2000;let b=10*w+6.25*h-5*a+5;let m=profile.activity==="Lightly Active"?1.375:profile.activity==="Very Active"?1.725:1.55;return Math.round(b*m)},[profile]);
 async function generatePlan(){setLoading(true);try{const r=await fetch(`${API}/assessment`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({goal,level})});if(!r.ok)throw Error();const d=await r.json();setPlan(d);setCompleted([]);setActivePage("dashboard");setShowAssessment(false);setToast("✓ Personalized plan generated") }catch{setPlan({...fallbackPlan,goal,level});setCompleted([]);setActivePage("dashboard");setShowAssessment(false);setToast("Starter plan loaded — backend unavailable")}finally{setLoading(false)}}
 function toggle(x){setCompleted(p=>p.includes(x)?p.filter(y=>y!==x):[...p,x])}
 function saveProfile(p){setProfile(p);setShowProfile(false);setToast("✓ Profile saved")}
 function nav(k){setActivePage(k);setShowProfile(false)}
 const first=(profile.name||"Fitness Explorer").split(" ")[0];
 return <div className={`app-shell ${darkMode?"theme-dark":"theme-light"}`}>
  <aside className="sidebar"><div className="brand"><div className="brand-orb"><span>FF</span></div><div><div className="brand-name">FITNESS FORGE</div><div className="brand-sub">TRAIN · TRACK · EVOLVE</div></div></div><div className="sidebar-label">WORKSPACE</div><nav className="nav-list">{navItems.map(([k,i,l])=><button key={k} className={`nav-item ${activePage===k?"active":""}`} onClick={()=>nav(k)}><span className="nav-icon">{i}</span><span>{l}</span>{k==="workouts"&&completion>0&&<em>{completion}%</em>}{activePage===k&&<i/>}</button>)}</nav><div className="sidebar-spacer"/><div className="forge-mini-card"><div className="mini-ring"><span>{plan.fitness_score}</span></div><div><b>Fitness Score</b><small>{goal}</small></div></div><div className="sidebar-user" onClick={()=>nav("profile")}><div className="user-avatar">{first[0]}</div><div><b>{profile.name}</b><small>Personal workspace</small></div></div><button className="theme-switch" onClick={()=>setDarkMode(v=>!v)}><span>{darkMode?"☀":"☾"}</span>{darkMode?"Light appearance":"Dark appearance"}</button></aside>
  <main className="main"><header className="topbar"><div className="breadcrumbs"><span>FITNESS FORGE</span><b>/</b><strong>{activePage.toUpperCase()}</strong></div><div className="topbar-actions"><div className={`api-pill ${apiOnline?"online":""}`}><span/>{apiOnline?"ENGINE ONLINE":"OFFLINE DEMO"}</div><button className="round-button" onClick={()=>setDarkMode(v=>!v)}>◐</button><div className="top-avatar" onClick={()=>nav("profile")}>{first[0]}</div></div></header>
   {activePage==="dashboard"&&<Dashboard plan={plan} completion={completion} exercises={exercises} completed={completed} toggle={toggle} setShowAssessment={setShowAssessment} nav={nav} first={first}/>} 
   {activePage==="workouts"&&<Workouts plan={plan} completed={completed} toggle={toggle} setShowAssessment={setShowAssessment}/>} 
   {activePage==="nutrition"&&<Nutrition calories={calories} profile={profile} goal={goal} setShowProfile={setShowProfile}/>} 
   {activePage==="progress"&&<Progress plan={plan} completed={completed} completion={completion}/>} 
   {activePage==="profile"&&<Profile profile={profile} setProfile={setProfile} goal={goal} setGoal={setGoal} level={level} setLevel={setLevel} save={()=>{localStorage.setItem("ff_profile",JSON.stringify(profile));setToast("✓ Profile saved")}}/>}
  </main>
  {showAssessment&&<Assessment goal={goal} setGoal={setGoal} level={level} setLevel={setLevel} loading={loading} close={()=>setShowAssessment(false)} generate={generatePlan}/>} 
  {showProfile&&<ProfileModal profile={profile} save={saveProfile} close={()=>setShowProfile(false)}/>} 
  {toast&&<div className="toast"><span>✦</span>{toast}</div>}
 </div>
}

function Dashboard({plan,completion,exercises,completed,toggle,setShowAssessment,nav,first}){return <div className="page"><section className="welcome-row"><div><div className="kicker">PERSONAL FITNESS OPERATING SYSTEM</div><h1>Good to see you, <em>{first}.</em></h1><p>Your dashboard for training, nutrition, progress and your next evolution.</p></div><button className="ghost-button" onClick={()=>setShowAssessment(true)}>✦ Reassess</button></section><section className="hero-panel"><div className="hero-grid-glow"/><div className="hero-copy"><div className="hero-chip"><span>✦</span> PERSONALIZED FITNESS</div><h2>Forge a body<br/><span>built for your goals.</span></h2><p>Turn your goal and fitness level into a personalized, measurable training journey.</p><div className="hero-actions"><button className="primary-button" onClick={()=>setShowAssessment(true)}>Start Assessment <span>→</span></button><button className="hero-secondary" onClick={()=>nav("progress")}>Explore progress</button></div><div className="hero-proof"><div className="proof-stack"><span>A</span><span>F</span><span>+</span></div><div><b>Built around you</b><small>Goal · Level · Progress · Consistency</small></div></div></div><div className="hero-visual"><div className="visual-grid"/><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="glow-ball ball-a"/><div className="glow-ball ball-b"/><div className="avatar-platform"><div className="platform-ring"/><div className="avatar-figure"><div className="avatar-head"/><div className="avatar-neck"/><div className="avatar-torso"/><div className="avatar-arm left"/><div className="avatar-arm right"/><div className="avatar-leg left"/><div className="avatar-leg right"/></div></div><div className="floating-metric score-card"><span>FITNESS SCORE</span><div><strong>{plan.fitness_score}</strong><small>/100</small></div><i><b/></i></div><div className="floating-metric level-card"><span>CURRENT LEVEL</span><strong>{plan.level}</strong><small>Adaptive plan</small></div><div className="floating-tag">↗ {completion}% <span>workout</span></div></div></section>
 <section className="metric-row"><Metric icon="🔥" label="WORKOUT STREAK" value="3" suffix="days" note="Keep the momentum"/><Metric icon="⚡" label="EXERCISES" value={`${completed.length}/${exercises.length}`} suffix="" note="Completed today"/><Metric icon="◈" label="CONSISTENCY" value={Math.max(62,completion)} suffix="%" note="This week"/><Metric icon="↗" label="PROGRESS" value="+12" suffix="%" note="Since starting"/></section>
 <section className="content-grid"><div className="panel workout-panel"><PanelHeading eyebrow="TODAY'S PLAN" title={plan.workout_type} right={<span className="duration">◷ {plan.duration}</span>}/><div className="workout-meta"><Meta label="GOAL" value={plan.goal}/><Meta label="LEVEL" value={plan.level}/><Meta label="INTENSITY" value={plan.intensity}/></div><div className="exercise-title"><div><b>Exercise sequence</b><span>Click an exercise when complete</span></div><span>{exercises.length} movements</span></div><div className="exercise-list">{exercises.map((x,i)=><button className={`exercise-row functional ${completed.includes(x)?"done":""}`} key={x} onClick={()=>toggle(x)}><div className="exercise-index">{String(i+1).padStart(2,"0")}</div><div className="exercise-symbol">{completed.includes(x)?"✓":["◒","◇","△","○"][i%4]}</div><div className="exercise-info"><b>{x}</b><span>{i===0?"Activation & warm-up":"Strength & conditioning"}</span></div><span className="exercise-time">{i===0?"5 min":"3 × 10"}</span><span className="exercise-arrow">{completed.includes(x)?"DONE":"→"}</span></button>)}</div><button className="wide-outline" onClick={()=>nav("workouts")}>Open full workout <span>→</span></button></div><div className="panel progress-panel"><PanelHeading eyebrow="YOUR PROGRESS" title="Growth overview" right={<span className="select-button">TODAY</span>}/><div className="score-highlight"><div><span>WORKOUT COMPLETE</span><b>{completion}<small>%</small></b></div><div className="score-change">{completed.length}/{exercises.length} done</div></div><div className="simple-progress"><i style={{width:`${completion}%`}}/></div><div className="progress-footer"><div><span>Strength</span><b>72%</b></div><div><span>Stamina</span><b>58%</b></div><div><span>Mobility</span><b>66%</b></div></div></div></section>
 <section className="smart-section"><div className="section-heading"><div><div className="kicker">THE NEXT EVOLUTION</div><h2>Intelligent fitness</h2></div><span>AI · VISION · 3D</span></div><div className="feature-grid"><Feature title="AI Fitness Coach" text="Rule-based today, AI personalization next." onClick={()=>setShowAssessment(true)}/><Feature title="Smart Nutrition" text="Open your daily energy and macro guide." onClick={()=>nav("nutrition")}/><Feature title="Evolving Avatar" text="Track your performance and future avatar." onClick={()=>nav("progress")}/></div></section></div>}

function Workouts({plan,completed,toggle,setShowAssessment}){return <div className="page module-page"><PageTitle kicker="TRAIN" title="Your workouts" text="Complete exercises to update your live progress." action={<button className="primary-button" onClick={()=>setShowAssessment(true)}>Change plan →</button>}/><div className="module-hero"><div><small>TODAY'S SESSION</small><h2>{plan.workout_type}</h2><p>{plan.goal} · {plan.level} · {plan.intensity} · {plan.duration}</p></div><strong>{plan.workout.length?Math.round(completed.filter(x=>plan.workout.includes(x)).length/plan.workout.length*100):0}%<small> complete</small></strong></div>{plan.workout.map((x,i)=><button key={x} className={`large-exercise ${completed.includes(x)?"done":""}`} onClick={()=>toggle(x)}><span>{String(i+1).padStart(2,"0")}</span><div><small>EXERCISE {i+1}</small><h3>{x}</h3><p>{i%2?"3 sets · 30 seconds":"3 sets · 10 reps"}</p></div><b>{completed.includes(x)?"✓ COMPLETED":"MARK DONE"}</b></button>)}</div>}
function Nutrition({calories,profile,goal,setShowProfile}){let protein=Math.round(calories*.25/4),carbs=Math.round(calories*.45/4),fat=Math.round(calories*.3/9);return <div className="page module-page"><PageTitle kicker="NOURISH" title="Nutrition" text="A starter nutrition view using your basic profile data." action={<button className="ghost-button" onClick={()=>setShowProfile(true)}>Update body data</button>}/><div className="nutrition-grid"><div className="panel big-nutrition"><small>ESTIMATED DAILY TARGET</small><strong>{calories.toLocaleString()}</strong><span> kcal / day</span><p>Estimate based on age, height, weight and activity level.</p></div><div className="panel macro-box"><h3>Macro guide</h3><Macro n="Protein" v={protein}/><Macro n="Carbohydrates" v={carbs}/><Macro n="Fats" v={fat}/></div></div><div className="panel future-box"><span>✦</span><div><h3>Smart Meal Analysis</h3><p>Next AI phase: upload a meal image to estimate calories, protein, carbs, fats and nutrients.</p></div><b>NEXT PHASE</b></div></div>}
function Progress({plan,completed,completion}){return <div className="page module-page"><PageTitle kicker="EVOLVE" title="Progress" text="Your progress updates from completed exercises."/><div className="nutrition-grid"><div className="panel big-progress"><small>TODAY'S COMPLETION</small><strong>{completion}%</strong><div className="simple-progress"><i style={{width:`${completion}%`}}/></div><p>{completed.length} of {plan.workout.length} exercises completed.</p></div><div className="panel stat-box"><h3>Fitness dimensions</h3><Macro n="Strength" v={72}/><Macro n="Stamina" v={58}/><Macro n="Mobility" v={66}/></div></div><div className="panel future-box"><span>◎</span><div><h3>Evolving Avatar</h3><p>Your future avatar can evolve from consistency, strength, stamina and mobility data.</p></div><b>ROADMAP</b></div></div>}
function Profile({profile,setProfile,goal,setGoal,level,setLevel,save}){return <div className="page module-page"><PageTitle kicker="YOU" title="Profile" text="Basic information helps personalize your fitness journey."/><div className="profile-grid"><div className="panel profile-card"><div className="profile-avatar">{(profile.name||"F")[0]}</div><h2>{profile.name}</h2><p>{goal} · {level}</p></div><div className="panel profile-form"><h3>Personal information</h3><div className="form-grid"><Field label="Name" value={profile.name} onChange={v=>setProfile({...profile,name:v})}/><Field label="Age" value={profile.age} onChange={v=>setProfile({...profile,age:v})}/><Field label="Height (cm)" value={profile.height} onChange={v=>setProfile({...profile,height:v})}/><Field label="Weight (kg)" value={profile.weight} onChange={v=>setProfile({...profile,weight:v})}/><Select label="Gender" value={profile.gender} onChange={v=>setProfile({...profile,gender:v})} options={["Prefer not to say","Female","Male"]}/><Select label="Activity" value={profile.activity} onChange={v=>setProfile({...profile,activity:v})} options={["Sedentary","Lightly Active","Moderately Active","Very Active"]}/></div><h3 className="sub">Fitness preferences</h3><div className="form-grid"><Select label="Goal" value={goal} onChange={setGoal} options={["General Fitness","Muscle Gain","Weight Loss"]}/><Select label="Fitness level" value={level} onChange={setLevel} options={["Beginner","Intermediate","Advanced"]}/></div><button className="primary-button save" onClick={save}>Save profile</button></div></div></div>}
function Assessment({goal,setGoal,level,setLevel,loading,close,generate}){return <div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={close}>×</button><div className="modal-orb">✦</div><div className="kicker">PERSONALIZATION ENGINE</div><h2>Build your plan.</h2><p>Choose your goal and fitness level. Your FastAPI engine will return the plan.</p><div className="form-block"><label>YOUR GOAL</label><div className="choice-grid">{["Muscle Gain","Weight Loss","General Fitness"].map(x=><button key={x} className={goal===x?"choice selected":"choice"} onClick={()=>setGoal(x)}>{x}<span>{goal===x?"✓":"+"}</span></button>)}</div></div><div className="form-block"><label>FITNESS LEVEL</label><div className="choice-grid">{["Beginner","Intermediate","Advanced"].map(x=><button key={x} className={level===x?"choice selected":"choice"} onClick={()=>setLevel(x)}>{x}<span>{level===x?"✓":"+"}</span></button>)}</div></div><div className="modal-note">✓ Rule-based personalization · FastAPI</div><button className="primary-button modal-submit" onClick={generate} disabled={loading}>{loading?"Building your plan...":"Generate my personalized plan →"}</button></div></div>}
function ProfileModal({profile,save,close}){const [p,setP]=useState(profile);return <div className="modal-backdrop"><div className="modal small-modal"><button className="modal-close" onClick={close}>×</button><div className="modal-orb">◎</div><div className="kicker">QUICK PROFILE</div><h2>Tell us about you.</h2><p>Height and weight help us create a better starter nutrition view.</p><div className="form-grid"><Field label="Name" value={p.name} onChange={v=>setP({...p,name:v})}/><Field label="Age" value={p.age} onChange={v=>setP({...p,age:v})}/><Field label="Height (cm)" value={p.height} onChange={v=>setP({...p,height:v})}/><Field label="Weight (kg)" value={p.weight} onChange={v=>setP({...p,weight:v})}/><Select label="Activity" value={p.activity} onChange={v=>setP({...p,activity:v})} options={["Sedentary","Lightly Active","Moderately Active","Very Active"]}/></div><button className="primary-button modal-submit" onClick={()=>save(p)}>Save information</button></div></div>}
function Field({label,value,onChange}){return <label className="field"><span>{label}</span><input value={value||""} onChange={e=>onChange(e.target.value)}/></label>}
function Select({label,value,onChange,options}){return <label className="field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Metric({icon,label,value,suffix,note}){return <div className="metric-card"><div className="metric-icon">{icon}</div><div><span>{label}</span><b>{value}<small>{suffix}</small></b><em>{note}</em></div></div>}
function Meta({label,value}){return <div><span>{label}</span><b>{value}</b></div>}
function PanelHeading({eyebrow,title,right}){return <div className="panel-heading"><div><div className="kicker">{eyebrow}</div><h2>{title}</h2></div>{right}</div>}
function PageTitle({kicker,title,text,action}){return <section className="module-title"><div><div className="kicker">{kicker}</div><h1>{title}</h1><p>{text}</p></div>{action}</section>}
function Macro({n,v}){return <div className="macro-row"><span>{n}</span><b>{v}g</b></div>}
function Feature({title,text,onClick}){return <div className="feature-card violet functional-card"><div className="feature-art"><div className="feature-orb"/><div className="feature-icon">✦</div><span>MODULE</span></div><h3>{title}</h3><p>{text}</p><button onClick={onClick}>Open module <span>→</span></button></div>}
export default App;
